EXPERIMENT:
  NAME: "gcam"
  TAG: "dev"
  PROJECT: "biased_mnist_baselines"
DATASET:
  TYPE: "biased_mnist"
  BIASES: ["color"]
  BIASED_MNIST:
    CORR: 0.99
MITIGATOR:
  TYPE: "gcam"
  GCOS:
    LAMBDA: 10.0
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 80
  LR: 0.001
  TYPE: "Adam"
  SCHEDULER:
    LR_DECAY_STAGES: [23, 56]
    LR_DECAY_RATE: 0.1
MODEL:
  TYPE: "simple_conv"
METRIC: "acc"