EXPERIMENT:
  NAME: "dino"
  TAG: "race"
  PROJECT: "utkface_baselines"
DATASET:
  TYPE: "utkface"
  UTKFACE:
    BIAS: "race"
    IMAGE_SIZE: 224
MITIGATOR:
  TYPE: "dino"
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 20
  LR: 0.001
  TYPE: "Adam"
  WEIGHT_DECAY: 1e-4
  SCHEDULER:
    LR_DECAY_STAGES: [6, 13]
    LR_DECAY_RATE: 0.1
MODEL:
  TYPE: "resnet18"
METRIC: "wg_ovr"

