EXPERIMENT:
  NAME: "mavias"
  TAG: "dev"
  PROJECT: "cifar100_baselines"
  EVAL: True
DATASET:
  TYPE: "cifar100"
  BIASES: ["unknown"]
MITIGATOR:
  TYPE: "mavias"
  MAVIAS:
    LOSS:
      ALPHA: 0.001
      LAMBDA: 0.8
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 60
  LR: 0.001
  WEIGHT_DECAY: 1e-4
  TYPE: "Adam"
  SCHEDULER:
    LR_DECAY_STAGES: [50]
    LR_DECAY_RATE: 0.1
MODEL:
  TYPE: "resnet20"
  PATH: "/mnt/cephfs/home/gsarridis/projects/vb-mitigator/output/cifar100_baselines/dev/mavias/best_vanilla"
METRIC: "wg_ovr"

