EXPERIMENT:
  NAME: "flac"
  TAG: "blonde"
  PROJECT: "celeba_baselines"
DATASET:
  TYPE: "celeba"
  BIASES: ["gender"]
  CELEBA:
    BIAS: "gender"
    TARGET: "blonde"
MITIGATOR:
  TYPE: "flac"
  FLAC:
    LOSS:
      ALPHA: 1000.0
      CE_WEIGHT: 1.0
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 70
  LR: 0.001
  TYPE: "Adam"
  SCHEDULER:
    LR_DECAY_STAGES: [60]
    LR_DECAY_RATE: 0.1
MODEL:
  TYPE: "resnet18"
METRIC: "unb_bc_ba"
