EXPERIMENT:
  NAME: "erm"
  TAG: "bcc"
  PROJECT: "jigsaw_toxic_comments_baselines"
DATASET:
  TYPE: "jigsaw_toxic_comments"
  NUM_WORKERS: 0
  BIASES: ["bias"]
  JIGSAW_TOXIC_COMMENTS:
    BIAS: "identity_hate"
    TARGET: "bias"
MITIGATOR:
  TYPE: "erm"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 200
  LR: 0.001
  TYPE: "Adam"
  WEIGHT_DECAY: 0.0
  SCHEDULER:
    LR_DECAY_STAGES: [70, 140]
    LR_DECAY_RATE: 0.1
MODEL:
  TYPE: "classification_head"
METRIC: "acc"
LOG:
  SAVE_CRITERION: "val"
  TRAIN_PERFORMANCE: True
