EXPERIMENT:
  NAME: "debian"
  TAG: "dev"
  PROJECT: "urbansounds_baselines"
DATASET:
  TYPE: "urbansounds"
  BIASES: ["bias"]
  NUM_WORKERS: 0
MITIGATOR:
  TYPE: "debian"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 100
  LR: 0.001
  TYPE: "Adam"
  WEIGHT_DECAY: 1e-4
  SCHEDULER:
    LR_DECAY_STAGES: [33, 66]
    LR_DECAY_RATE: 0.1
MODEL:
  TYPE: "cnn_classifier_mfcc"
METRIC: "wg_ovr"
LOG:
  SAVE_CRITERION: "test"