EXPERIMENT:
  NAME: "maviasb"
  TAG: "multi"
  PROJECT: "imagenet9m_baselines"
DATASET:
  TYPE: "imagenet9m"
  BIASES: ["jpeg", "resize"]
  IMAGENET9M:
    SCENARIO: "multi"
    CLASSES: [1, 5]
    CORRELATION_JPEG: 0.99
    CORRELATION_RESIZE: 0.99
    # multi uses exactly 2 bias classes per type (index 0 -> target 0, index 1 -> target 1)
    JPEG_CLASSES: [[95, "4:4:4"], [75, "4:2:0"]]
    RESIZE_CLASSES: [2.0, 0.5]
MITIGATOR:
  TYPE: "maviasb"
  MAVIASB: 
    BCC_PATHS:                                                  
      - "./output/imagenet9m_baselines/bcc_jpeg/erm/best"    
      - "./output/imagenet9m_baselines/bcc_resize/erm/best"   
    LOSS:
      ALPHA: 0.01
      LAMBDA: 0.5
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 30
  LR: 0.001
  TYPE: "Adam"
  WEIGHT_DECAY: 1e-4
  SCHEDULER:
    LR_DECAY_STAGES: [25]
    LR_DECAY_RATE: 0.1
MODEL:
  TYPE: "resnet18"
  PRETRAINED: False
METRIC: "wg_ovr"
