EXPERIMENT:
  NAME: "jtt"
  TAG: "race"
  PROJECT: "utkface_baselines"
DATASET:
  TYPE: "utkface"
  UTKFACE:
    BIAS: "race"
MITIGATOR:
  TYPE: "jtt"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 100
  LR: 0.00001
  TYPE: "SGD"
  WEIGHT_DECAY: 1.0
  SCHEDULER:
    LR_DECAY_STAGES: [10000]
    LR_DECAY_RATE: 0.1
MODEL:
  TYPE: "resnet18"
METRIC: "wg_ovr"
LOG:
  TRAIN_PERFORMANCE: True
