EXPERIMENT:
  NAME: "flac"
  TAG: "bench"
  PROJECT: "urbancars_baselines"
DATASET:
  TYPE: "urbancars"
  BIASES: ["background","object"]
MITIGATOR:
  TYPE: "flac"
  FLAC:
    LOSS:
      ALPHA: 10000.0
      CE_WEIGHT: 1.0
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 150
  LR: 0.001
  TYPE: "SGD"
  WEIGHT_DECAY: 1e-4
  SCHEDULER:
    LR_DECAY_STAGES: [1000]
    LR_DECAY_RATE: 0.1
MODEL:
  TYPE: "resnet50"
  PRETRAINED: True
METRIC: "wg_ovr"

