EXPERIMENT:
  NAME: "flacb"
  TAG: "bench"
  PROJECT: "waterbirds_baselines"
DATASET:
  TYPE: "waterbirds"
  BIASES: ["background"]
MITIGATOR:
  TYPE: "flacb"
  FLACB:
    BCC_PATH: "./output/waterbirds_baselines/bench/erm/best"
    LOSS:
      ALPHA: 10000.0
      CE_WEIGHT: 1.0
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 100
  TYPE: "SGD"
  WEIGHT_DECAY: 1e-4
  SCHEDULER:
    LR_DECAY_STAGES: [1000]
    LR_DECAY_RATE: 0.1
MODEL:
  TYPE: "resnet50"
  PRETRAINED: True
  FREEZE_BACKBONE: False
METRIC: "wg_ovr"
