EXPERIMENT:
  NAME: "mhmavias"
  TAG: "dev"
  PROJECT: "biased_mnist_baselines"
DATASET:
  TYPE: "biased_mnist"
MITIGATOR:
  TYPE: "mhmavias"
  MHMAVIAS:
    LOSS:
      ALPHA: 0.01
      LAMBDA: 0.4
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 80
  LR: 0.001
  TYPE: "Adam"
  SCHEDULER:
    LR_DECAY_STAGES: [27, 54]
    LR_DECAY_RATE: 0.1
MODEL:
  TYPE: "simple_conv_mh"
METRIC: "acc"
LOG:
  TRAIN_PERFORMANCE: True