EXPERIMENT:
  NAME: "erm"
  TAG: "dev"
  PROJECT: "urbansounds58_baselines"
DATASET:
  TYPE: "urbansounds58"
  BIASES: ["bias"]
  NUM_WORKERS: 0
MITIGATOR:
  TYPE: "erm"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 100
  LR: 0.001
  TYPE: "SGD"
  WEIGHT_DECAY:  1e-4
  SCHEDULER:
    LR_DECAY_STAGES: [33, 66]
    LR_DECAY_RATE: 0.1
MODEL:
  TYPE: "cnn_classifier_mfcc"
METRIC: "wg_ovr"
LOG:
  SAVE_CRITERION: "test"

