EXPERIMENT:
  NAME: "erm"
  TAG: "dev"
  PROJECT: "stanford_dogs_baselines"
DATASET:
  TYPE: "stanford_dogs"
  BIASES: ["unknown"]
MITIGATOR:
  TYPE: "erm"
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 20
  LR: 0.001
  TYPE: "Adam"
  WEIGHT_DECAY: 0.0
  SCHEDULER:
    LR_DECAY_STAGES: [15]
    LR_DECAY_RATE: 0.1
MODEL:
  TYPE: "resnet18"
  PRETRAINED: True
METRIC: "acc"
