EXPERIMENT:
  NAME: "badd"
  TAG: "dev"
  PROJECT: "biased_mnist_baselines"
DATASET:
  TYPE: "biased_mnist"
  BIASES: ["color"]
MITIGATOR:
  TYPE: "badd"
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 80
  LR: 0.001
  TYPE: "Adam"
  SCHEDULER:
    LR_DECAY_STAGES: [27, 54]
    LR_DECAY_RATE: 0.1
MODEL:
  TYPE: "simple_conv"
METRIC: "acc"
