EXPERIMENT:
  NAME: "mavias"
  TAG: "dev"
  PROJECT: "waterbirds_baselines"
DATASET:
  TYPE: "waterbirds"
  BIASES: ["background"]
MITIGATOR:
  TYPE: "mavias"
  MAVIAS:
    LOSS:
      ALPHA: 0.05
      LAMBDA: 0.6
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 100
  TYPE: "SGD"
  WEIGHT_DECAY: 1e-4
  SCHEDULER:
    LR_DECAY_STAGES: [1000]
    LR_DECAY_RATE: 0.1
MODEL:
  TYPE: "resnet50"
  PRETRAINED: True
  FREEZE_BACKBONE: False
METRIC: "wg_ovr_tags"