EXPERIMENT:
  NAME: "maviasb"
  TAG: "dev"
  PROJECT: "jigsaw_toxic_comments_baselines"
DATASET:
  TYPE: "jigsaw_toxic_comments"
  BIASES: ["bias"]
  NUM_WORKERS: 0
MITIGATOR:
  TYPE: "maviasb"
  MAVIASB: 
    BCC_PATH: "./output/jigsaw_toxic_comments_baselines/bcc/erm/best"
    LOSS:
      ALPHA: 0.01
      LAMBDA: 0.5
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 200
  LR: 0.001
  TYPE: "Adam"
  WEIGHT_DECAY: 1e-2
  SCHEDULER:
    LR_DECAY_STAGES: [70, 140]
    LR_DECAY_RATE: 0.1
MODEL:
  TYPE: "classification_head"
METRIC: "acc"
LOG:
  SAVE_CRITERION: "val"
