EXPERIMENT:
  NAME: "erm"
  TAG: "bcc"
  PROJECT: "chexpert_nih_baselines"
DATASET:
  TYPE: "chexpert_nih"
  NUM_WORKERS: 0
  BIASES: ["bias"]
MITIGATOR:
  TYPE: "erm_bcc"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 20
  LR: 0.001
  TYPE: "Adam"
  WEIGHT_DECAY: 0.0
  SCHEDULER:
    LR_DECAY_STAGES: [3, 6]
    LR_DECAY_RATE: 0.1
MODEL:
    TYPE: "resnet18"
    PRETRAINED: True
METRIC: "acc"
LOG:
  SAVE_CRITERION: "test"
  TRAIN_PERFORMANCE: True
