EXPERIMENT:
  NAME: "lr"
  TAG: "race"
  PROJECT: "utkface_baselines"
DATASET:
  TYPE: "utkface"
  UTKFACE:
    BIAS: "race"
MITIGATOR:
  TYPE: "lr"
SOLVER:
  BATCH_SIZE: 128
  EPOCHS: 20
  LR: 0.001
  TYPE: "SGD"
  WEIGHT_DECAY: 0.0001
  SCHEDULER:
    LR_DECAY_STAGES: [6, 13]
    LR_DECAY_RATE: 0.1
MODEL:
  TYPE: "resnet18"
METRIC: "wg_ovr"
