EXPERIMENT:
  NAME: "flac"
  TAG: "dev"
  PROJECT: "speech_accent_archive_baselines"
DATASET:
  TYPE: "speech_accent_archive"
  BIASES: ["bias"]
MITIGATOR:
  TYPE: "flac"
  FLAC: 
    BCC_PATH: "./output/speech_accent_archive_baselines/bcc/erm/latest"
    LOSS:
      ALPHA: 1000.0
      CE_WEIGHT: 1.0
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 100
  LR: 0.001
  TYPE: "Adam"
  WEIGHT_DECAY: 0.0
  SCHEDULER:
    LR_DECAY_STAGES: [33, 66]
    LR_DECAY_RATE: 0.1
MODEL:
  TYPE: "lstm_classifier"
METRIC: "wg_ovr"
LOG:
  SAVE_CRITERION: "test"
